### PR TITLE
Update Project-Id-Version of po files

### PR DESCRIPTION
**Pull request by andreldm**
This is shot in the dark, I didn't even test it, hopefully it works :)

### CODE REVIEW

**Comment by Skunnyk** [comment]
Nice usage of pcregrep, I didn't know that tool :)
However: not all projects are using configure.ac.in (see catfish, tumbler etc).
Also, it fails to match correct version on components with 4.13.x scheme (double digit) !
```
xfce4-appfinder: $ pcregrep -o2  "m4_define.*_version_(major|minor|micro).*(\d)" configure.ac.in                                                                               
4
3
1
4 
```
The last '4' digit is here because it match another m4_define occurrence .

**Comment by andreldm** [comment]
You're right, please see the new commits.

**Comment by Skunnyk** [comment]
Still the problem to parse 4.13.3 for example ;)
BTW, not sure it is really necessary to extract exact version, the resource name should be enough ?

**Comment by andreldm** [comment]
Meh, I tried to make things right, but I don't really mind one way or the other.
Even the guy that pointed this out suggested to do as Transifex (supposedly) does, use the project's category, e.g. "Xfce Apps".

**Comment by andreldm** [comment]
@Skunnyk after two years, I don't even remember what I was trying to fix here, closing :D

**Pull request closed without merging**
